### ISSUE TITLE
Article structure

### ISSUE THREAD

**Issue by jstac** [QuantEcon/qe_libraries_article#1]
Suggested structure from @smit-create, copied from https://github.com/QuantEcon/meta/issues/71

Just a suggestion -- as a basic outline we can divide this article into the following sections:
1. Abstract
2. Introduction and Background
3. QuantEcon capalabilites
    - [x] `markov` (#6 )
    - [x] `optimize` (#7 )
    - [x] `game_theory`
    - [x] `miscellaneous`
4. Architecture (we can include some details like using `numpy`/`numba` etc.)
5. Some benchmark results (speed results with and without `numba` or comparison with other libraries if exist.)
6. Future Work (maybe compatibility with GPU or Jax.)

**Comment by Smit-create** [comment]
I have opened a sample PR #6 which tries to include `markov`. For now, I have added the `MarkovChain` details and if that looks good, I can start working in a similar fashion to complete the `markov` sub-package. Please have a look and let me know if you have any suggestions like adding more details, adding more code, etc.

**Comment by Smit-create** [comment]
@oyamad Can you please highlight the 2-3 functions from `game_theory` that you would like to have in the article? I can add that using the documentation.

**Comment by Smit-create** [comment]
I'll try to wrap up points 4 and 5 soon together and I think we will be close to the finish line of a very rough first draft.

**Comment by jstac** [comment]
Thanks @Smit-create.  If you can put a rough draft together I will step in and do the next pass.

**Comment by oyamad** [comment]
Thanks @Smit-create! Just a few random "highlights":

* The main aim of the `game_theory` submodule is to provide efficient implementation of state-of-the-art algorithms for computing Nash equilibria of normal form games, relying only on "standard" libraries (i.e., those that are available in the default Anaconda distribution) such as `NumPy` and `SciPy`, while leveraging `Numba`'s JIT compilation technology wherever possible.
* Currently, `game_theory` contains, among some others, implementations of:
  - support and vertex enumeration algorithms, `support_enumeration` and `vertex_enumeration`, for computing all Nash equilibria of a (non-degenerate) normal form game with two players;
  - the Lemke-Howson algorithm, `lemke_howson`, for computing one Nash equilibrium of a normal form game with two players; and
  - the McLennan-Tourky algorithm, `mclennan_tourky`, for computing one Nash equilibrium of a normal form game with N players.

  In particular, `lemke_howson` scales up to games with several hundreds actions.
* It also contains several learning/evolutionary dynamics algorithms, such as fictitious play (and its stochastic version), best response dynamics (and its stochastic version), local interaction dynamics, and logit response dynamics.
* Possible future projects include adding more equilibrium computation algorithms for N-player games and supporting extensive form games.
* (If we also talk about Julia versions, `GameTheory.jl` has a few more interesting implementations, thanks to a larger variety of available packages in Julia (where there is an official collection of packages which we can freely depend on).)
* It is to apply not only to this submodule, but to the whole `QuantEcon.py` package, that we strictly restrict ourselves to depend only on libraries available in Anaconda for installation and maintenance ease, while we try our best not to sacrifice the efficiency (speed) of the code by using `Numba`. I think this point should be emphasized in the paper.

These are just random sentences, not meant to be included as is. Please elaborate and edit them...

**Comment by Smit-create** [comment]
Many thanks, @oyamad. I'll try to frame some sentences around this to include in the article.

**Comment by Smit-create** [comment]
@jstac I have added some sections so we can see a rough idea of the article. It still needs some information from your end like Abstract, Introduction, Future work, and if you are interested in adding something like: https://www.nature.com/articles/s41592-019-0686-2#Sec28. Thanks! Please let me know if you want to add anything else.

Also, we need to decide whether to keep it limited to `QuantEcon.py` or also add something about `QuantEcon.jl`.
