### ISSUE TITLE
Start article with template -- aimed at JOSS?

### ISSUE THREAD

**Issue by jstac** [QuantEcon/qe_libraries_article#2]
JOSS seems to suggest an MD template: https://joss.readthedocs.io/en/latest/submitting.html

Compilation is via a GH action: https://joss.readthedocs.io/en/latest/submitting.html#github-action

Perhaps @mmcky might kick this process off?

**Comment by Smit-create** [comment]
This is fixed in #4. To view the draft paper on CI:
1. Click on Actions tab.
2. Select the GH action run for commit you want to view.
3. Scroll at the bottom once the CI passes where you can find `paper.zip`.
