### ISSUE TITLE
Some comments for discussion

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/qe_libraries_article#21]
1. Title
   Rather than just "QuantEcon", maybe more descriptive "QuantEcon.py: A community based Python library for quantitative economics" or something would be better?
2. The current version refers to the submodules (`game_theory`, `markov`, and others) as "major modules". I thought these were put into submodules just for maintenance reasons, and we didn't mean the top level routines were "minor"?
3. As future projects, only projects from game theory are mentioned. To have a good balance, it would be better to have a few more from other fields?
4. References that are not referred to in the text should not be listed.

**Comment by Smit-create** [comment]
Thanks @oyamad 

> Rather than just "QuantEcon", maybe more descriptive "QuantEcon.py: A community based Python library for quantitative economics" or something would be better?

Sounds good to me.

> References that are not referred to in the text should not be listed.

@jstac also mentioned this and needs to be fixed. @HumphreyYang and I will look into it.

**Comment by HumphreyYang** [comment]
Many thanks @Smit-create,

I have looked over the updated references. It looks great to me. I will add in some more at places like Tauchen's method.
