### ISSUE TITLE
Authors and collaborators

### ISSUE THREAD

**Issue by jstac** [QuantEcon/qe_libraries_article#3]
I think it's fine for us to have a very large list of co-authors.  See, e.g., https://arxiv.org/abs/2206.14220

Suggested authors, in no particular order, include

@mmcky 
@oyamad 
@jlperla 
@smit-create
@thomassargent30 
@sglyon 
@cc7768
@albop
@natashawatkins
@jstac 

Quentin Batista (@QBatista)
YuyaFurusawa (@Yuya-Furusawa)
Zejin Shi (@shizejin)
...

Please add, including other developers in https://quantecon.org/team/.  

@jlperla , do you have time for this if we all write small parts?  @smit-create is volunteering to get things started.  Please feel free to add co-authors.

**Comment by jstac** [comment]
@albop, @cc7768, @sglyon, @natashawatkins, @thomassargent30  the paper is basically done (see https://github.com/QuantEcon/qe_libraries_article/blob/main/paper.md) and we will submit to JOSS in a week or so.  If you would like to be coauthors (which I hope you will be), then please add your name and affiliation to the paper (edit paper.md).

Feel free to add edits too.

**Comment by jstac** [comment]
Ditto for  other coauthors now listed in the manuscript.

**Comment by natashawatkins** [comment]
This is cool -- thanks!! Just to confirm, if my name is already there, do I need to do anything?

**Comment by jstac** [comment]
@natashawatkins Please add your affiliation if it's not there.

**Comment by natashawatkins** [comment]
@mmcky is there a difference between index and affiliation?

**Comment by Smit-create** [comment]
I have an open PR #12. If anyone wants to add their affiliation please comment on the PR and I'll push those changes. Thanks!

**Comment by jstac** [comment]
Sorry @Smit-create , I merged it :-)

I've reverted so please open a new PR and tell us the number again.

**Comment by Smit-create** [comment]
No worries! Please comment on #14  for missing/incorrect affiliations. Thanks!

**Comment by mmcky** [comment]
> @mmcky is there a difference between index and affiliation?

@natashawatkins As far as I understand the metadata format there is a list of affiliations and a list of authors linked by an id number. Fill in the affiliation in that logic and we can take it from there.
